export const CartActionTypes = {
  CART_TOGGLE_VISIBILITY: 'CART_TOGGLE_VISIBILITY',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART'
}